# Generated by Django 4.2.7 on 2023-12-07 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(default='UnknownCompany', max_length=100)),
                ('description', models.TextField()),
                ('job_type', models.CharField(choices=[('Tiempo Completo', 'Tiempo Completo'), ('Medio Tiempo', 'Medio Tiempo'), ('Becario', 'Becario'), ('Temporal', 'Temporal'), ('Contrato', 'Contrato')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employer_profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='employers.employerprofile')),
            ],
        ),
    ]
